-- MySQL Script generated by MySQL Workbench
-- Sun Jan  5 17:12:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Table_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_students` (
  `idTable_students` INT NOT NULL,
  `Surname` VARCHAR(45) NULL,
  `First_name` VARCHAR(45) NULL,
  `Date_of_birth` DATETIME NULL,
  PRIMARY KEY (`idTable_students`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_courses` (
  `idTable_courses` INT NOT NULL,
  `Label` VARCHAR(45) NULL,
  `Coefficient` INT NULL,
  `Date` DATETIME NULL,
  PRIMARY KEY (`idTable_courses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_courses` (
  `idTable_courses` INT NOT NULL,
  `Label` VARCHAR(45) NULL,
  `Coefficient` INT NULL,
  `Date` DATETIME NULL,
  PRIMARY KEY (`idTable_courses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_follow` (
  `Table_courses_idTable_courses` INT NOT NULL,
  `Table_students_idTable_students` INT NOT NULL,
  `score` INT NULL,
  PRIMARY KEY (`Table_courses_idTable_courses`, `Table_students_idTable_students`),
  INDEX `fk_Table_courses_has_Table_students_Table_students2_idx` (`Table_students_idTable_students` ASC) VISIBLE,
  INDEX `fk_Table_courses_has_Table_students_Table_courses1_idx` (`Table_courses_idTable_courses` ASC) VISIBLE,
  CONSTRAINT `fk_Table_courses_has_Table_students_Table_courses1`
    FOREIGN KEY (`Table_courses_idTable_courses`)
    REFERENCES `mydb`.`Table_courses` (`idTable_courses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Table_courses_has_Table_students_Table_students2`
    FOREIGN KEY (`Table_students_idTable_students`)
    REFERENCES `mydb`.`Table_students` (`idTable_students`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_follow` (
  `Table_courses_idTable_courses` INT NOT NULL,
  `Table_students_idTable_students` INT NOT NULL,
  `score` INT NULL,
  PRIMARY KEY (`Table_courses_idTable_courses`, `Table_students_idTable_students`),
  INDEX `fk_Table_courses_has_Table_students_Table_students2_idx` (`Table_students_idTable_students` ASC) VISIBLE,
  INDEX `fk_Table_courses_has_Table_students_Table_courses1_idx` (`Table_courses_idTable_courses` ASC) VISIBLE,
  CONSTRAINT `fk_Table_courses_has_Table_students_Table_courses1`
    FOREIGN KEY (`Table_courses_idTable_courses`)
    REFERENCES `mydb`.`Table_courses` (`idTable_courses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Table_courses_has_Table_students_Table_students2`
    FOREIGN KEY (`Table_students_idTable_students`)
    REFERENCES `mydb`.`Table_students` (`idTable_students`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_class_degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_class_degree` (
  `idTable_class_degree` INT NOT NULL,
  `Level` INT NULL,
  `Table_students_idTable_students` INT NOT NULL,
  PRIMARY KEY (`idTable_class_degree`, `Table_students_idTable_students`),
  INDEX `fk_Table_class_degree_Table_students1_idx` (`Table_students_idTable_students` ASC) VISIBLE,
  CONSTRAINT `fk_Table_class_degree_Table_students1`
    FOREIGN KEY (`Table_students_idTable_students`)
    REFERENCES `mydb`.`Table_students` (`idTable_students`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_instruments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_instruments` (
  `idTable_instruments` INT NOT NULL,
  `Label` VARCHAR(45) NULL,
  `Table_students_idTable_students` INT NOT NULL,
  PRIMARY KEY (`idTable_instruments`, `Table_students_idTable_students`),
  INDEX `fk_Table_instruments_Table_students1_idx` (`Table_students_idTable_students` ASC) VISIBLE,
  CONSTRAINT `fk_Table_instruments_Table_students1`
    FOREIGN KEY (`Table_students_idTable_students`)
    REFERENCES `mydb`.`Table_students` (`idTable_students`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_classrooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_classrooms` (
  `idTable_classrooms` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Capicity_max` INT NULL,
  `Table_courses_idTable_courses` INT NOT NULL,
  PRIMARY KEY (`idTable_classrooms`, `Table_courses_idTable_courses`),
  INDEX `fk_Table_classrooms_Table_courses1_idx` (`Table_courses_idTable_courses` ASC) VISIBLE,
  CONSTRAINT `fk_Table_classrooms_Table_courses1`
    FOREIGN KEY (`Table_courses_idTable_courses`)
    REFERENCES `mydb`.`Table_courses` (`idTable_courses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_teachers` (
  `idTable_teachers` INT NOT NULL,
  `Surname` VARCHAR(45) NULL,
  `First_name` VARCHAR(45) NULL,
  `Date_of_birth` DATETIME NULL,
  `Table_courses_idTable_courses` INT NOT NULL,
  PRIMARY KEY (`idTable_teachers`, `Table_courses_idTable_courses`),
  INDEX `fk_Table_teachers_Table_courses1_idx` (`Table_courses_idTable_courses` ASC) VISIBLE,
  CONSTRAINT `fk_Table_teachers_Table_courses1`
    FOREIGN KEY (`Table_courses_idTable_courses`)
    REFERENCES `mydb`.`Table_courses` (`idTable_courses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
