-- MySQL Script generated by MySQL Workbench
-- Sun Jan 12 19:31:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Table_instruments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_instruments` (
  `idTable_instruments` INT NOT NULL,
  `Label` VARCHAR(45) NULL,
  PRIMARY KEY (`idTable_instruments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_class_degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_class_degree` (
  `idTable_class_degree` INT NOT NULL,
  `Level` INT NULL,
  PRIMARY KEY (`idTable_class_degree`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_students` (
  `idTable_students` INT NOT NULL,
  `Surname` VARCHAR(45) NULL,
  `First_name` VARCHAR(45) NULL,
  `Date_of_birth` VARCHAR(45) NULL,
  `Table_instruments_idTable_instruments` INT NOT NULL,
  `Table_class_degree_idTable_class_degree` INT NOT NULL,
  PRIMARY KEY (`idTable_students`, `Table_instruments_idTable_instruments`, `Table_class_degree_idTable_class_degree`),
  INDEX `fk_Table_students_Table_instruments1_idx` (`Table_instruments_idTable_instruments` ASC) VISIBLE,
  INDEX `fk_Table_students_Table_class_degree1_idx` (`Table_class_degree_idTable_class_degree` ASC) VISIBLE,
  CONSTRAINT `fk_Table_students_Table_instruments1`
    FOREIGN KEY (`Table_instruments_idTable_instruments`)
    REFERENCES `mydb`.`Table_instruments` (`idTable_instruments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Table_students_Table_class_degree1`
    FOREIGN KEY (`Table_class_degree_idTable_class_degree`)
    REFERENCES `mydb`.`Table_class_degree` (`idTable_class_degree`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_courses` (
  `idTable_courses` INT NOT NULL,
  `Label` VARCHAR(45) NULL,
  `Coefficient` INT NULL,
  PRIMARY KEY (`idTable_courses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_courses` (
  `idTable_courses` INT NOT NULL,
  `Label` VARCHAR(45) NULL,
  `Coefficient` INT NULL,
  PRIMARY KEY (`idTable_courses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_follow` (
  `Table_courses_idTable_courses` INT NOT NULL,
  `Table_students_idTable_students` INT NOT NULL,
  PRIMARY KEY (`Table_courses_idTable_courses`, `Table_students_idTable_students`),
  INDEX `fk_Table_courses_has_Table_students_Table_students1_idx` (`Table_students_idTable_students` ASC) VISIBLE,
  INDEX `fk_Table_courses_has_Table_students_Table_courses_idx` (`Table_courses_idTable_courses` ASC) VISIBLE,
  CONSTRAINT `fk_Table_courses_has_Table_students_Table_courses`
    FOREIGN KEY (`Table_courses_idTable_courses`)
    REFERENCES `mydb`.`Table_courses` (`idTable_courses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Table_courses_has_Table_students_Table_students1`
    FOREIGN KEY (`Table_students_idTable_students`)
    REFERENCES `mydb`.`Table_students` (`idTable_students`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_follow_mark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_follow_mark` (
  `Table_courses_idTable_courses` INT NOT NULL,
  `Table_students_idTable_students` INT NOT NULL,
  `score` INT NULL,
  PRIMARY KEY (`Table_courses_idTable_courses`, `Table_students_idTable_students`),
  INDEX `fk_Table_courses_has_Table_students_Table_students2_idx` (`Table_students_idTable_students` ASC) VISIBLE,
  INDEX `fk_Table_courses_has_Table_students_Table_courses1_idx` (`Table_courses_idTable_courses` ASC) VISIBLE,
  CONSTRAINT `fk_Table_courses_has_Table_students_Table_courses1`
    FOREIGN KEY (`Table_courses_idTable_courses`)
    REFERENCES `mydb`.`Table_courses` (`idTable_courses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Table_courses_has_Table_students_Table_students2`
    FOREIGN KEY (`Table_students_idTable_students`)
    REFERENCES `mydb`.`Table_students` (`idTable_students`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_classrooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_classrooms` (
  `idTable_classrooms` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Capacity_max` INT NULL,
  PRIMARY KEY (`idTable_classrooms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_take_place_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_take_place_courses` (
  `Table_classrooms_idTable_classrooms` INT NOT NULL,
  `Table_courses_idTable_courses` INT NOT NULL,
  `Date` VARCHAR(45) NULL,
  PRIMARY KEY (`Table_classrooms_idTable_classrooms`, `Table_courses_idTable_courses`),
  INDEX `fk_Table_classrooms_has_Table_courses_Table_courses1_idx` (`Table_courses_idTable_courses` ASC) VISIBLE,
  INDEX `fk_Table_classrooms_has_Table_courses_Table_classrooms1_idx` (`Table_classrooms_idTable_classrooms` ASC) VISIBLE,
  CONSTRAINT `fk_Table_classrooms_has_Table_courses_Table_classrooms1`
    FOREIGN KEY (`Table_classrooms_idTable_classrooms`)
    REFERENCES `mydb`.`Table_classrooms` (`idTable_classrooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Table_classrooms_has_Table_courses_Table_courses1`
    FOREIGN KEY (`Table_courses_idTable_courses`)
    REFERENCES `mydb`.`Table_courses` (`idTable_courses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_teachers` (
  `idTable_teachers` INT NOT NULL,
  `Surname` VARCHAR(45) NULL,
  `First_name` VARCHAR(45) NULL,
  `Date_of_birth` VARCHAR(45) NULL,
  PRIMARY KEY (`idTable_teachers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table_courses_has_Table_teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table_courses_has_Table_teachers` (
  `Table_courses_idTable_courses` INT NOT NULL,
  `Table_teachers_idTable_teachers` INT NOT NULL,
  PRIMARY KEY (`Table_courses_idTable_courses`, `Table_teachers_idTable_teachers`),
  INDEX `fk_Table_courses_has_Table_teachers_Table_teachers1_idx` (`Table_teachers_idTable_teachers` ASC) VISIBLE,
  INDEX `fk_Table_courses_has_Table_teachers_Table_courses1_idx` (`Table_courses_idTable_courses` ASC) VISIBLE,
  CONSTRAINT `fk_Table_courses_has_Table_teachers_Table_courses1`
    FOREIGN KEY (`Table_courses_idTable_courses`)
    REFERENCES `mydb`.`Table_courses` (`idTable_courses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Table_courses_has_Table_teachers_Table_teachers1`
    FOREIGN KEY (`Table_teachers_idTable_teachers`)
    REFERENCES `mydb`.`Table_teachers` (`idTable_teachers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
